"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""
# Intialize varibales
first = 0
second = 1
next = 0
sum = 0
Number = 4000000 # Number assigned to four million
# Check if next number will exceed four million
while (first + second) < Number:
    next = first + second
    first = second
    second = next
    # Check if fibonacci number is even-valued number
    if (next % 2 == 0):
        sum = sum + next
print (sum)